# Generated by Django 3.0 on 2019-12-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('viable', models.BooleanField(default=True)),
                ('groundType', models.CharField(choices=[('SAND', 'Sandy soil'), ('CLAY', 'Clay Soil'), ('SILT', 'Silt Soil'), ('PEAT', 'Peat Soil'), ('CHALK', 'Chalk Soil'), ('LOAM', 'Loam Soil')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootType', models.CharField(choices=[('TAP', 'taproot'), ('FIB', 'fibrous'), ('ADV', 'adventitious')], max_length=3)),
                ('groundLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Ground')),
            ],
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachedRoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Root')),
            ],
        ),
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_type', models.CharField(choices=[('ALT', 'Alternate'), ('OPO', 'Opposite'), ('WHO', 'Whorled'), ('BAC', 'Basal')], max_length=3)),
                ('attached_to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='attached_trunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Trunk'),
        ),
    ]
