# Generated by Django 3.0 on 2019-12-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20191218_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='connected_trunk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exercise.Trunk'),
            preserve_default=False,
        ),
    ]
