# Generated by Django 3.0 on 2019-12-19 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_tree_connected_trunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ground',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='tree',
            name='connected_trunk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercise.Trunk'),
        ),
    ]
