# Generated by Django 3.0 on 2019-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20191219_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_healty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='length',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='branch',
            name='width',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='ground',
            name='latitude',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='ground',
            name='longitude',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='leaf',
            name='surface',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='trunk',
            name='age',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='trunk',
            name='diameter',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
