# Generated by Django 3.0 on 2019-12-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20191219_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ground',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
    ]
