# Generated by Django 3.0 on 2019-12-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20191219_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ground',
            options={'verbose_name_plural': 'Soils'},
        ),
    ]
