# Generated by Django 3.0 on 2019-12-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20191221_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ground',
            options={'verbose_name_plural': 'Soil types'},
        ),
        migrations.AlterField(
            model_name='ground',
            name='groundType',
            field=models.CharField(choices=[('SAND', 'Sandy soil'), ('CLAY', 'Clay Soil'), ('SILT', 'Silt Soil'), ('PEAT', 'Peat Soil'), ('CHALK', 'Chalk Soil'), ('LOAM', 'Loam Soil')], default='SAND', max_length=5),
        ),
    ]
